title: sinthetix computers.
description: |
  **Hey! I'm sinthetix**, but you can call me Aly or Thix. I'm a computerer at [Travis CI](https://travis-ci.com) and here is where I brain dump all the things!
    
    **[About](http://sinthetix.github.io/about.html)**
    **[Talks](http://sinthetix.github.io/talks.html)**
copyright: 2016 Aly Fulton
sass:
  sass_dir: assets/sass
url: http://sinthetix.github.io
disqus_shortname: 
facebook_username:
twitter_username: sinthetix
linkedin_username: 
instagram_username:
pinterest_username:
flickr_username:
github_username:  sinthetix
feed_icon: rss
email: aly@travis-ci.com
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
