title: sinthetix computers.
description: >
  **Hey, I'm Aly.** I'm a computerer at [Travis CI](https://travis-ci.com). Here is where I brain dump!
copyright: 2016 sinthetix
sass:
  sass_dir: assets/sass
url: https://sinthetix.github.io
disqus_shortname: 
facebook_username:
twitter_username: sinthetix
linkedin_username: 
instagram_username:
pinterest_username:
flickr_username:
github_username:  sinthetix
feed_icon: rss
email: 
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
