title: sinthetix computers.
description: |
  **Hey! I'm sinthetix**, but you can call me Aly or Thix. I'm a computerer and here is where I brain dump all the things. You can also view my **[full bio](http://sinthetix.github.io/bio.html)** or my **[talks](http://sinthetix.github.io/talks.html)**.
copyright: 2016 Aly Fulton
sass:
  sass_dir: assets/sass
url: http://sinthetix.github.io
disqus_shortname: 
facebook_username:
twitter_username: sinthetix
linkedin_username: sinthetix
instagram_username:
pinterest_username:
flickr_username:
github_username:  sinthetix
feed_icon: rss
email: aly@obeythelime.com
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
